import React from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  OffthreadVideo,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import {loadFont as loadCaveat} from "@remotion/google-fonts/Caveat";
// Generated by scripts/build_preview_data.py — do not edit by hand.
import previewData from "./data/preview-data.json";

const {fontFamily: CAVEAT_FAMILY} = loadCaveat("normal", {weights: ["700"]});

/**
 * Spoolcast composition.
 *
 * Per-chunk:
 * - image = pre-gen stroke-reveal frame during wipe-in/wipe-out, otherwise static PNG
 * - camera (x, y, zoom) interpolated per beat from the shot list's
 *   camera_target / camera_zoom / transition_s fields
 * - if no beats in the chunk have camera targets, falls back to a subtle
 *   push-in (1.0 → 1.08 over the chunk duration) so the image never feels dead
 */

export const SPOOLCAST_FPS: number = previewData.fps;
export const SPOOLCAST_DURATION_IN_FRAMES: number = Math.max(
  1,
  previewData.totalFrames
);
// Canvas dimensions resolved from session config + aspect_ratio in
// build_preview_data.py. Defaults to 1920x1080 if not present (legacy data).
export const SPOOLCAST_WIDTH: number =
  (previewData as {width?: number}).width ?? 1920;
export const SPOOLCAST_HEIGHT: number =
  (previewData as {height?: number}).height ?? 1080;

// Zone vocabulary → (x, y) center of frame to focus on, as percentages
const ZONES: Record<string, {x: number; y: number}> = {
  center: {x: 50, y: 50},
  "left-third": {x: 17, y: 50},
  "right-third": {x: 83, y: 50},
  "top-third": {x: 50, y: 17},
  "bottom-third": {x: 50, y: 83},
  "upper-middle": {x: 50, y: 30},
  "lower-middle": {x: 50, y: 70},
  "top-left": {x: 20, y: 22},
  "top-right": {x: 80, y: 22},
  "bottom-left": {x: 20, y: 78},
  "bottom-right": {x: 80, y: 78},
  left: {x: 25, y: 50},
  right: {x: 75, y: 50},
  top: {x: 50, y: 25},
  bottom: {x: 50, y: 75},
};

const ZOOMS: Record<string, number> = {
  "": 1.0,
  wide: 1.0,
  medium: 1.35,
  tight: 1.9,
  close: 2.8,
};

type Beat = {
  id: string;
  audioSrc: string;
  audioDurationSec: number;
  startFrameInChunk: number;
  endFrameInChunk: number;
  pauseFrames: number;
  camera?: {
    reason: string;
    target: string;
    zoom: string;
    zoomValue?: number;
    transitionSec: number;
  };
};

type Overlay = {
  src: string;
  startFrameInChunk: number;
  endFrameInChunk: number;
  x: number;
  y: number;
  anchor: string; // "top-right" | "top-left" | "bottom-right" | "bottom-left" | "center"
  width: number;  // fraction of canvas width
  entryTransition?: string;
  exitTransition?: string;
};

type Chunk = {
  id: string;
  imageSrc: string;
  imageSource?: string; // "generated" | "broll" | "meme" | "broll_image" | ...
  brollFraming?: string | null; // "tv" | null
  startFromSec?: number; // for broll video: seconds into source to begin playback
  overlays?: Overlay[];
  startFrame: number;
  durationFrames: number;
  continuity?: string;
  entrance?: string;
  exit?: string;
  wipeInFrames?: number;
  wipeOutFrames?: number;
  framesDir?: string;
  preGenFrameCount?: number;
  beats: Beat[];
  boundary_kind?: string;
  act_title?: string;
  weight?: string;
};

type CameraState = {x: number; y: number; zoom: number};

const DEFAULT_CAMERA: CameraState = {x: 50, y: 50, zoom: 1.0};

function cameraFromBeat(beat: Beat): CameraState | null {
  const cam = beat.camera;
  if (!cam || !cam.target) return null;
  const zone = ZONES[cam.target] ?? ZONES.center;
  const zoom = ZOOMS[cam.zoom] ?? 1.0;
  return {x: zone.x, y: zone.y, zoom};
}

function lerpCam(a: CameraState, b: CameraState, t: number): CameraState {
  const k = Math.max(0, Math.min(1, t));
  return {
    x: a.x + (b.x - a.x) * k,
    y: a.y + (b.y - a.y) * k,
    zoom: a.zoom + (b.zoom - a.zoom) * k,
  };
}

function easeInOut(t: number): number {
  return 0.5 - 0.5 * Math.cos(Math.PI * Math.max(0, Math.min(1, t)));
}

/** Returns camera state at a given frame within a chunk, interpolating
 *  between beat targets. If no beats set a camera, returns a subtle push-in. */
function computeCamera(
  chunk: Chunk,
  frameInChunk: number,
  fps: number
): CameraState {
  const beats = chunk.beats;
  const beatCameras = beats.map((b) => cameraFromBeat(b));
  const anySet = beatCameras.some((c) => c !== null);

  if (!anySet) {
    // continues-from-prev / callbacks: hold steady at 1.0. Cuts between
    // similar/continuing images get jarring when each chunk independently
    // pushes in from 1.0 — the camera "rewinds" on every cut.
    const cont = chunk.continuity || "standalone";
    if (cont === "continues-from-prev" || cont.startsWith("callback")) {
      return {x: 50, y: 50, zoom: 1.0};
    }
    // Standalone / new chunks: subtle push-in from 1.0 to 1.08
    const t = Math.max(0, Math.min(1, frameInChunk / Math.max(1, chunk.durationFrames)));
    return {x: 50, y: 50, zoom: 1.0 + 0.08 * t};
  }

  // Find the active beat at this frame (last beat whose start <= frame)
  let active = 0;
  for (let i = 0; i < beats.length; i++) {
    if (beats[i].startFrameInChunk <= frameInChunk) active = i;
  }
  const activeBeat = beats[active];
  const activeCam = beatCameras[active] ?? DEFAULT_CAMERA;

  // Find previous set camera (for interpolation) — walk back to find one
  let prevCam: CameraState = DEFAULT_CAMERA;
  for (let i = active - 1; i >= 0; i--) {
    if (beatCameras[i]) {
      prevCam = beatCameras[i] as CameraState;
      break;
    }
  }
  // If active beat has no camera set, inherit previous
  if (!beatCameras[active]) {
    return prevCam;
  }

  const transitionFrames = Math.round(
    (activeBeat.camera?.transitionSec ?? 0) * fps
  );
  if (transitionFrames <= 0) {
    return activeCam;
  }

  const t = easeInOut(
    (frameInChunk - activeBeat.startFrameInChunk) / transitionFrames
  );
  return lerpCam(prevCam, activeCam, t);
}

/** CSS transform that zooms so the target (x%, y%) of the image appears
 *  at the center of the viewport. */
function cameraTransform(
  cam: CameraState,
  viewportW: number,
  viewportH: number
): string {
  const dx = ((50 - cam.x) / 100) * viewportW * cam.zoom;
  const dy = ((50 - cam.y) / 100) * viewportH * cam.zoom;
  return `translate(${dx}px, ${dy}px) scale(${cam.zoom})`;
}

// For generated (16:9) chunks with camera zoom, `cover` fills cleanly.
const IMG_STYLE: React.CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "cover",
  display: "block",
};

// For memes, static external screenshots, and anything with non-16:9 source
// aspect. Uses `contain` so the full image shows, with black letterbox where
// the source doesn't match the canvas.
const CONTAIN_STYLE: React.CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "contain",
  display: "block",
};

// imageSource values that should use the letterboxed "contain" style instead
// of the default `cover` (which crops).
const LETTERBOX_SOURCES = new Set([
  "meme",
  "external_screenshot",
  "external_xlsx",
  "external_json",
  "external_terminal",
  "broll_image",
  "composite_pilot",
  "broll",
]);

function anchorToOffsets(anchor: string): {tx: string; ty: string} {
  // Returns CSS translate offsets to position the overlay so its specified
  // anchor point sits at (x, y). Because we position by top/left on the box,
  // we need to shift the box itself via translate.
  switch (anchor) {
    case "top-left":     return {tx: "0%",    ty: "0%"};
    case "top-right":    return {tx: "-100%", ty: "0%"};
    case "bottom-left":  return {tx: "0%",    ty: "-100%"};
    case "bottom-right": return {tx: "-100%", ty: "-100%"};
    case "center":
    default:             return {tx: "-50%",  ty: "-50%"};
  }
}

const OverlayLayer: React.FC<{overlays: Overlay[]; canvasWidth: number; canvasHeight: number}> = ({
  overlays,
  canvasWidth,
  canvasHeight,
}) => {
  const frame = useCurrentFrame();
  if (!overlays || overlays.length === 0) return null;
  return (
    <>
      {overlays.map((ov, i) => {
        if (frame < ov.startFrameInChunk || frame >= ov.endFrameInChunk) return null;
        const w = ov.width * canvasWidth;
        const px = ov.x * canvasWidth;
        const py = ov.y * canvasHeight;
        const {tx, ty} = anchorToOffsets(ov.anchor);
        return (
          <div
            key={`${ov.src}-${i}`}
            style={{
              position: "absolute",
              left: px,
              top: py,
              width: w,
              transform: `translate(${tx}, ${ty})`,
            }}
          >
            <Img
              src={staticFile(ov.src)}
              style={{width: "100%", height: "auto", display: "block"}}
            />
          </div>
        );
      })}
    </>
  );
};

const TVFrameWrapper: React.FC<{children: React.ReactNode}> = ({children}) => {
  // Greyed background + centered styled frame at ~80% width.
  return (
    <AbsoluteFill style={{backgroundColor: "#2a2a2a"}}>
      <div
        style={{
          position: "absolute",
          left: "50%",
          top: "50%",
          transform: "translate(-50%, -50%)",
          width: "80%",
          aspectRatio: "16/9",
          background: "#000",
          border: "8px solid #ddd",
          borderRadius: "14px",
          boxShadow: "0 12px 40px rgba(0,0,0,0.5), inset 0 0 0 2px #111",
          overflow: "hidden",
        }}
      >
        {children}
      </div>
    </AbsoluteFill>
  );
};

const BumperRenderer: React.FC<{chunk: Chunk}> = ({chunk}) => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 8], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const title = chunk.act_title ?? "";
  // Rough estimate of text width so the underline scales proportionally to
  // the title. 140px font with Caveat averages ~0.5em per glyph.
  const approxTextWidth = Math.max(200, title.length * 70);
  const underlineWidth = approxTextWidth * 0.6;
  // White background to match the rest of the notebook-doodle video.
  const INK = "#111111";
  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#ffffff",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <div
        style={{
          opacity,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            fontFamily: CAVEAT_FAMILY,
            fontSize: 220,
            fontWeight: 700,
            color: INK,
            lineHeight: 1.1,
            textAlign: "center",
          }}
        >
          {title}
        </div>
        <div
          style={{
            width: underlineWidth,
            height: 8,
            backgroundColor: INK,
            borderRadius: 4,
            transform: "rotate(-0.7deg)",
            marginTop: 24,
          }}
        />
      </div>
    </AbsoluteFill>
  );
};

const ChunkRenderer: React.FC<{chunk: Chunk}> = ({chunk}) => {
  if (chunk.boundary_kind === "bumper") {
    return <BumperRenderer chunk={chunk} />;
  }
  const frame = useCurrentFrame();
  const {width, height, fps} = useVideoConfig();
  const wipeIn = chunk.wipeInFrames ?? 0;
  const wipeOut = chunk.wipeOutFrames ?? 0;
  const dur = chunk.durationFrames;
  const wipeOutStart = dur - wipeOut;
  const preGen = chunk.preGenFrameCount ?? 0;
  const framesDir = chunk.framesDir ?? "";
  const hasFrames = preGen > 0 && framesDir !== "";
  const imageSource = chunk.imageSource || "generated";
  const isBrollVideo = imageSource === "broll" && /\.(mp4|mov|webm)$/i.test(chunk.imageSrc);

  const inWipeIn = wipeIn > 0 && frame < wipeIn;
  const inWipeOut = wipeOut > 0 && frame >= wipeOutStart;

  let srcPath = chunk.imageSrc;
  if (hasFrames && !isBrollVideo && inWipeIn) {
    const progress = Math.min(1, Math.max(0, frame / wipeIn));
    const idx = Math.max(1, Math.min(preGen, Math.ceil(progress * preGen)));
    srcPath = `${framesDir}/frame_${String(idx).padStart(4, "0")}.png`;
  }
  // Wipe-out: fade the final image uniformly to white via opacity.
  // Previously we replayed reveal-in frames in reverse, which looked wrong
  // because outlines and fills have different reveal-times in the stroke
  // reveal — reverse-playing made fills disappear instantly while outlines
  // lingered. Uniform opacity fade treats every pixel the same. See
  // STORY.md § Part 2 (wipe-out behavior).
  const wipeOutOpacity = inWipeOut
    ? Math.max(0, 1 - (frame - wipeOutStart) / Math.max(1, wipeOut))
    : 1;

  const cam = computeCamera(chunk, frame, fps);
  const transform = cameraTransform(cam, width, height);

  // --- content: either video playback (broll) or image ---
  let content: React.ReactNode;
  if (isBrollVideo) {
    content = (
      <OffthreadVideo
        src={staticFile(chunk.imageSrc)}
        startFrom={Math.max(0, Math.round((chunk.startFromSec ?? 0) * fps))}
        style={{width: "100%", height: "100%", objectFit: "contain", display: "block"}}
      />
    );
    if (chunk.brollFraming === "tv") {
      content = <TVFrameWrapper>{content}</TVFrameWrapper>;
    }
  } else {
    const useLetterbox = LETTERBOX_SOURCES.has(imageSource);
    const style = useLetterbox ? CONTAIN_STYLE : IMG_STYLE;
    content = (
      <div
        style={{
          width: "100%",
          height: "100%",
          transform: useLetterbox ? "none" : transform,
          transformOrigin: "50% 50%",
        }}
      >
        <Img src={staticFile(srcPath)} style={style} />
      </div>
    );
  }

  // Letterboxed content needs a black background; illustrated (cover) content
  // uses white to match the notebook-doodle style.
  const useLetterbox = LETTERBOX_SOURCES.has(imageSource);
  const bg = useLetterbox ? "#000000" : "#ffffff";

  return (
    <AbsoluteFill style={{backgroundColor: bg, overflow: "hidden"}}>
      <div style={{width: "100%", height: "100%", opacity: wipeOutOpacity}}>
        {content}
        <OverlayLayer
          overlays={chunk.overlays || []}
          canvasWidth={width}
          canvasHeight={height}
        />
      </div>
    </AbsoluteFill>
  );
};

export const SpoolcastComposition: React.FC = () => {
  const chunks = previewData.chunks as Chunk[];
  const playbackRate: number =
    (previewData as {playbackRate?: number}).playbackRate ?? 1.0;

  return (
    <AbsoluteFill style={{backgroundColor: "#ffffff"}}>
      {chunks.map((chunk) => (
        <Sequence
          key={chunk.id}
          from={chunk.startFrame}
          durationInFrames={chunk.durationFrames}
        >
          <ChunkRenderer chunk={chunk} />
          {chunk.beats.map((beat) => {
            // Skip audio for placeholder beats (broll chunks with no narration mp3).
            if (!beat.audioSrc) return null;
            return (
              <Sequence
                key={beat.id}
                from={beat.startFrameInChunk}
                durationInFrames={Math.max(
                  1,
                  beat.endFrameInChunk - beat.startFrameInChunk
                )}
              >
                <Audio
                  src={staticFile(beat.audioSrc)}
                  playbackRate={playbackRate}
                />
              </Sequence>
            );
          })}
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
