import React from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  OffthreadVideo,
  Sequence,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import {loadFont as loadCaveat} from "@remotion/google-fonts/Caveat";
// Generated by scripts/build_preview_data.py — do not edit by hand.
import previewData from "./data/preview-data.json";

const {fontFamily: CAVEAT_FAMILY} = loadCaveat("normal", {weights: ["700"]});

/**
 * Spoolcast composition.
 *
 * Per-chunk:
 * - image = pre-gen stroke-reveal frame during wipe-in/wipe-out, otherwise static PNG
 * - camera (x, y, zoom) interpolated per beat from the shot list's
 *   camera_target / camera_zoom / transition_s fields
 * - if no beats in the chunk have camera targets, falls back to a subtle
 *   push-in (1.0 → 1.08 over the chunk duration) so the image never feels dead
 */

export const SPOOLCAST_FPS: number = previewData.fps;
export const SPOOLCAST_DURATION_IN_FRAMES: number = Math.max(
  1,
  previewData.totalFrames
);
// Canvas dimensions resolved from session config + aspect_ratio in
// build_preview_data.py. Defaults to 1920x1080 if not present (legacy data).
export const SPOOLCAST_WIDTH: number =
  (previewData as {width?: number}).width ?? 1920;
export const SPOOLCAST_HEIGHT: number =
  (previewData as {height?: number}).height ?? 1080;

// Zone vocabulary → (x, y) center of frame to focus on, as percentages
const ZONES: Record<string, {x: number; y: number}> = {
  center: {x: 50, y: 50},
  "left-third": {x: 17, y: 50},
  "right-third": {x: 83, y: 50},
  "top-third": {x: 50, y: 17},
  "bottom-third": {x: 50, y: 83},
  "upper-middle": {x: 50, y: 30},
  "lower-middle": {x: 50, y: 70},
  "top-left": {x: 20, y: 22},
  "top-right": {x: 80, y: 22},
  "bottom-left": {x: 20, y: 78},
  "bottom-right": {x: 80, y: 78},
  left: {x: 25, y: 50},
  right: {x: 75, y: 50},
  top: {x: 50, y: 25},
  bottom: {x: 50, y: 75},
};

const ZOOMS: Record<string, number> = {
  "": 1.0,
  wide: 1.0,
  medium: 1.35,
  tight: 1.9,
  close: 2.8,
};

type Beat = {
  id: string;
  audioSrc: string;
  audioDurationSec: number;
  startFrameInChunk: number;
  endFrameInChunk: number;
  pauseFrames: number;
  camera?: {
    reason: string;
    target: string;
    zoom: string;
    zoomValue?: number;
    transitionSec: number;
  };
};

type Overlay = {
  src: string;
  startFrameInChunk: number;
  endFrameInChunk: number;
  x: number;
  y: number;
  anchor: string; // "top-right" | "top-left" | "bottom-right" | "bottom-left" | "center"
  width: number;  // fraction of canvas width
  rotationDeg?: number;
  entryTransition?: string;
  exitTransition?: string;
};

// Cross-chunk overlay: top-level, lives outside any chunk's Sequence so it can
// span chunk boundaries without resetting its video clock at the cut.
// See rules.md § Meme placement option (4).
type CrossChunkOverlay = {
  src: string;
  absStartFrame: number;
  absEndFrame: number;
  x: number;
  y: number;
  anchor: string;
  width: number;
  rotationDeg?: number;
  entryTransition?: string;
  exitTransition?: string;
};

type Chunk = {
  id: string;
  imageSrc: string;
  imageSource?: string; // "generated" | "broll" | "meme" | "broll_image" | ...
  brollFraming?: string | null; // "tv-screen" | "full-frame" | "inset" | null — see PIPELINE.md § broll_framing
  startFromSec?: number; // for broll video: seconds into source to begin playback
  overlays?: Overlay[];
  startFrame: number;
  durationFrames: number;
  continuity?: string;
  entrance?: string;
  exit?: string;
  wipeInFrames?: number;
  wipeOutFrames?: number;
  crossfadeInFrames?: number;
  crossfadeOutFrames?: number;
  priorFinalImageSrc?: string;
  framesDir?: string;
  preGenFrameCount?: number;
  beats: Beat[];
  boundary_kind?: string;
  act_title?: string;
  weight?: string;
  punchline?: boolean;
  reveal_group?: string;
};

type CameraState = {x: number; y: number; zoom: number};

const DEFAULT_CAMERA: CameraState = {x: 50, y: 50, zoom: 1.0};

function cameraFromBeat(beat: Beat): CameraState | null {
  const cam = beat.camera;
  if (!cam || !cam.target) return null;
  const zone = ZONES[cam.target] ?? ZONES.center;
  const zoom = ZOOMS[cam.zoom] ?? 1.0;
  return {x: zone.x, y: zone.y, zoom};
}

function lerpCam(a: CameraState, b: CameraState, t: number): CameraState {
  const k = Math.max(0, Math.min(1, t));
  return {
    x: a.x + (b.x - a.x) * k,
    y: a.y + (b.y - a.y) * k,
    zoom: a.zoom + (b.zoom - a.zoom) * k,
  };
}

function easeInOut(t: number): number {
  return 0.5 - 0.5 * Math.cos(Math.PI * Math.max(0, Math.min(1, t)));
}

/** Returns camera state at a given frame within a chunk, interpolating
 *  between beat targets. If no beats set a camera, returns a subtle push-in. */
function computeCamera(
  chunk: Chunk,
  frameInChunk: number,
  fps: number
): CameraState {
  const beats = chunk.beats;
  const beatCameras = beats.map((b) => cameraFromBeat(b));
  const anySet = beatCameras.some((c) => c !== null);

  if (!anySet) {
    // continues-from-prev / callbacks: hold steady at 1.0. Cuts between
    // similar/continuing images get jarring when each chunk independently
    // pushes in from 1.0 — the camera "rewinds" on every cut.
    const cont = chunk.continuity || "standalone";
    if (cont === "continues-from-prev" || cont.startsWith("callback")) {
      return {x: 50, y: 50, zoom: 1.0};
    }
    // Standalone / new chunks: subtle push-in from 1.0 to 1.08
    const t = Math.max(0, Math.min(1, frameInChunk / Math.max(1, chunk.durationFrames)));
    return {x: 50, y: 50, zoom: 1.0 + 0.08 * t};
  }

  // Find the active beat at this frame (last beat whose start <= frame)
  let active = 0;
  for (let i = 0; i < beats.length; i++) {
    if (beats[i].startFrameInChunk <= frameInChunk) active = i;
  }
  const activeBeat = beats[active];
  const activeCam = beatCameras[active] ?? DEFAULT_CAMERA;

  // Find previous set camera (for interpolation) — walk back to find one
  let prevCam: CameraState = DEFAULT_CAMERA;
  for (let i = active - 1; i >= 0; i--) {
    if (beatCameras[i]) {
      prevCam = beatCameras[i] as CameraState;
      break;
    }
  }
  // If active beat has no camera set, inherit previous
  if (!beatCameras[active]) {
    return prevCam;
  }

  const transitionFrames = Math.round(
    (activeBeat.camera?.transitionSec ?? 0) * fps
  );
  if (transitionFrames <= 0) {
    return activeCam;
  }

  const t = easeInOut(
    (frameInChunk - activeBeat.startFrameInChunk) / transitionFrames
  );
  return lerpCam(prevCam, activeCam, t);
}

/** CSS transform that zooms so the target (x%, y%) of the image appears
 *  at the center of the viewport. */
function cameraTransform(
  cam: CameraState,
  viewportW: number,
  viewportH: number
): string {
  const dx = ((50 - cam.x) / 100) * viewportW * cam.zoom;
  const dy = ((50 - cam.y) / 100) * viewportH * cam.zoom;
  return `translate(${dx}px, ${dy}px) scale(${cam.zoom})`;
}

// For generated (16:9) chunks with camera zoom, `cover` fills cleanly.
const IMG_STYLE: React.CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "cover",
  display: "block",
};

// For memes, static external screenshots, and anything with non-16:9 source
// aspect. Uses `contain` so the full image shows, with black letterbox where
// the source doesn't match the canvas.
const CONTAIN_STYLE: React.CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "contain",
  display: "block",
};

// imageSource values that should use the letterboxed "contain" style instead
// of the default `cover` (which crops).
const LETTERBOX_SOURCES = new Set([
  "meme",
  "external_screenshot",
  "external_xlsx",
  "external_json",
  "external_terminal",
  "broll_image",
  "composite_pilot",
  "broll",
]);

function anchorToOffsets(anchor: string): {tx: string; ty: string} {
  // Returns CSS translate offsets to position the overlay so its specified
  // anchor point sits at (x, y). Because we position by top/left on the box,
  // we need to shift the box itself via translate.
  switch (anchor) {
    case "top-left":     return {tx: "0%",    ty: "0%"};
    case "top-right":    return {tx: "-100%", ty: "0%"};
    case "bottom-left":  return {tx: "0%",    ty: "-100%"};
    case "bottom-right": return {tx: "-100%", ty: "-100%"};
    case "center":
    default:             return {tx: "-50%",  ty: "-50%"};
  }
}

const OverlayLayer: React.FC<{overlays: Overlay[]; canvasWidth: number; canvasHeight: number}> = ({
  overlays,
  canvasWidth,
  canvasHeight,
}) => {
  if (!overlays || overlays.length === 0) return null;
  return (
    <>
      {overlays.map((ov, i) => {
        const w = ov.width * canvasWidth;
        const px = ov.x * canvasWidth;
        const py = ov.y * canvasHeight;
        const {tx, ty} = anchorToOffsets(ov.anchor);
        const rot = ov.rotationDeg ?? 0;
        const lower = ov.src.toLowerCase();
        const isVideo = lower.endsWith(".mp4") || lower.endsWith(".webm") || lower.endsWith(".mov");
        // Wrap each overlay in its own Sequence so video overlays get a
        // time origin starting at zero when they appear. Without this,
        // OffthreadVideo plays based on the parent chunk's frame and a
        // late-mounted overlay would skip past the source duration and
        // freeze on the last frame.
        return (
          <Sequence
            key={`${ov.src}-${i}`}
            from={ov.startFrameInChunk}
            durationInFrames={Math.max(1, ov.endFrameInChunk - ov.startFrameInChunk)}
            layout="none"
          >
            <div
              style={{
                position: "absolute",
                left: px,
                top: py,
                width: w,
                transform: `translate(${tx}, ${ty}) rotate(${rot}deg)`,
                transformOrigin: "center center",
              }}
            >
              {isVideo ? (
                <OffthreadVideo
                  src={staticFile(ov.src)}
                  style={{width: "100%", height: "auto", display: "block"}}
                  muted
                />
              ) : (
                <Img
                  src={staticFile(ov.src)}
                  style={{width: "100%", height: "auto", display: "block"}}
                />
              )}
            </div>
          </Sequence>
        );
      })}
    </>
  );
};

const TVFrameWrapper: React.FC<{
  children: React.ReactNode;
  playbackIcon?: boolean;
}> = ({children, playbackIcon = false}) => {
  // Greyed background + centered styled frame at ~80% width. Optional rewind
  // icon in the bottom-right corner of the screen to signal "this is a replay"
  // (used when the broll asset is a video clip from a prior video; see
  // VISUALS.md § Previous-video broll framing).
  return (
    <AbsoluteFill style={{backgroundColor: "#2a2a2a"}}>
      <div
        style={{
          position: "absolute",
          left: "50%",
          top: "50%",
          transform: "translate(-50%, -50%)",
          width: "80%",
          aspectRatio: "16/9",
          background: "#000",
          border: "8px solid #ddd",
          borderRadius: "14px",
          boxShadow: "0 12px 40px rgba(0,0,0,0.5), inset 0 0 0 2px #111",
          overflow: "hidden",
        }}
      >
        {children}
        {playbackIcon ? (
          <div
            style={{
              position: "absolute",
              right: 18,
              bottom: 14,
              display: "flex",
              alignItems: "center",
              gap: 8,
              padding: "6px 12px",
              borderRadius: 8,
              backgroundColor: "rgba(0,0,0,0.55)",
              backdropFilter: "blur(2px)",
              fontFamily: "monospace",
              fontSize: 22,
              fontWeight: 700,
              letterSpacing: 1,
              color: "#ff4a4a",
              textShadow: "0 0 6px rgba(255,74,74,0.35)",
              pointerEvents: "none",
            }}
          >
            <svg
              width="26"
              height="22"
              viewBox="0 0 26 22"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
            >
              <polygon points="13,2 2,11 13,20" fill="#ff4a4a" />
              <polygon points="25,2 14,11 25,20" fill="#ff4a4a" />
            </svg>
            <span>REC</span>
          </div>
        ) : null}
      </div>
    </AbsoluteFill>
  );
};

const BumperRenderer: React.FC<{chunk: Chunk}> = ({chunk}) => {
  // Bumpers are title cards — they snap in at full opacity. A fade-in
  // against a white bg produces an all-white first frame (the audit
  // catches that as a flash). Chapter headings don't need a soft entrance
  // anyway; the hard cut IS the "new act starts" signal.
  const opacity = 1;
  const title = chunk.act_title ?? "";
  // Rough estimate of text width so the underline scales proportionally to
  // the title. 140px font with Caveat averages ~0.5em per glyph.
  const approxTextWidth = Math.max(200, title.length * 70);
  const underlineWidth = approxTextWidth * 0.6;
  // White background to match the rest of the notebook-doodle video.
  const INK = "#111111";
  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#ffffff",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <div
        style={{
          opacity,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            fontFamily: CAVEAT_FAMILY,
            fontSize: 220,
            fontWeight: 700,
            color: INK,
            lineHeight: 1.1,
            textAlign: "center",
          }}
        >
          {title}
        </div>
        <div
          style={{
            width: underlineWidth,
            height: 8,
            backgroundColor: INK,
            borderRadius: 4,
            transform: "rotate(-0.7deg)",
            marginTop: 24,
          }}
        />
      </div>
    </AbsoluteFill>
  );
};

const ChunkRenderer: React.FC<{chunk: Chunk; priorChunk: Chunk | null}> = ({
  chunk,
  priorChunk,
}) => {
  if (chunk.boundary_kind === "bumper") {
    return <BumperRenderer chunk={chunk} />;
  }
  const frame = useCurrentFrame();
  const {width, height, fps} = useVideoConfig();
  const wipeIn = chunk.wipeInFrames ?? 0;
  const wipeOut = chunk.wipeOutFrames ?? 0;
  const dur = chunk.durationFrames;
  const wipeOutStart = dur - wipeOut;
  const preGen = chunk.preGenFrameCount ?? 0;
  const framesDir = chunk.framesDir ?? "";
  const hasFrames = preGen > 0 && framesDir !== "";
  const imageSource = chunk.imageSource || "generated";
  const isBrollVideo = imageSource === "broll" && /\.(mp4|mov|webm)$/i.test(chunk.imageSrc);

  const inWipeIn = wipeIn > 0 && frame < wipeIn;
  const inWipeOut = wipeOut > 0 && frame >= wipeOutStart;

  // Crossfade: entrance-side effect. When entrance === "crossfade" and we
  // have a priorFinalImageSrc, render the prior chunk's last frame as an
  // underlay and ramp this chunk's opacity from 0 → 1 over the first
  // crossfadeInFrames. See VISUALS.md § Inter-chunk transition vocabulary.
  const crossfadeIn = chunk.crossfadeInFrames ?? 0;
  const entrance = chunk.entrance ?? "cut";
  const isCrossfadeEntrance = entrance === "crossfade" && crossfadeIn > 0;
  const crossfadeInOpacity = isCrossfadeEntrance
    ? Math.min(1, Math.max(0, frame / crossfadeIn))
    : 1;
  const inCrossfadeIn = isCrossfadeEntrance && frame < crossfadeIn;

  let srcPath = chunk.imageSrc;
  if (hasFrames && !isBrollVideo && inWipeIn) {
    const progress = Math.min(1, Math.max(0, frame / wipeIn));
    const idx = Math.max(1, Math.min(preGen, Math.ceil(progress * preGen)));
    srcPath = `${framesDir}/frame_${String(idx).padStart(4, "0")}.png`;
  }
  // Wipe-out: fade the final image uniformly to white via opacity.
  // Previously we replayed reveal-in frames in reverse, which looked wrong
  // because outlines and fills have different reveal-times in the stroke
  // reveal — reverse-playing made fills disappear instantly while outlines
  // lingered. Uniform opacity fade treats every pixel the same. See
  // STORY.md § Part 2 (wipe-out behavior).
  const wipeOutOpacity = inWipeOut
    ? Math.max(0, 1 - (frame - wipeOutStart) / Math.max(1, wipeOut))
    : 1;

  const cam = computeCamera(chunk, frame, fps);
  const transform = cameraTransform(cam, width, height);

  // --- content: either video playback (broll) or image ---
  // TV-frame wrapping applies to sibling-video / self-reject broll regardless
  // of whether the asset is a video clip or a still (see VISUALS.md §
  // Previous-video broll framing). Schema value "tv-screen" is the canonical;
  // legacy "tv" is accepted as an alias.
  const wantsTvFrame =
    chunk.brollFraming === "tv-screen" || chunk.brollFraming === "tv";
  let content: React.ReactNode;
  if (isBrollVideo) {
    content = (
      <OffthreadVideo
        src={staticFile(chunk.imageSrc)}
        startFrom={Math.max(0, Math.round((chunk.startFromSec ?? 0) * fps))}
        style={{width: "100%", height: "100%", objectFit: "contain", display: "block"}}
      />
    );
    if (wantsTvFrame) {
      // Video broll gets the REC indicator — it's a moving playback of a
      // prior recording, and the icon signals "this is a replay."
      content = <TVFrameWrapper playbackIcon>{content}</TVFrameWrapper>;
    }
  } else {
    const useLetterbox = LETTERBOX_SOURCES.has(imageSource);
    const style = useLetterbox ? CONTAIN_STYLE : IMG_STYLE;
    content = (
      <div
        style={{
          width: "100%",
          height: "100%",
          transform: useLetterbox ? "none" : transform,
          transformOrigin: "50% 50%",
        }}
      >
        <Img src={staticFile(srcPath)} style={style} />
      </div>
    );
    if (wantsTvFrame) {
      // Still broll (broll_image): no REC indicator — a still frame can't
      // be "playing," so the indicator would feel wrong. The frame itself
      // carries the "this is from another video" signal.
      content = <TVFrameWrapper>{content}</TVFrameWrapper>;
    }
  }

  // Letterboxed content needs a black background; illustrated (cover) content
  // uses white to match the notebook-doodle style.
  const useLetterbox = LETTERBOX_SOURCES.has(imageSource);
  const bg = useLetterbox ? "#000000" : "#ffffff";

  // Prior-frame underlay: visible only during the crossfade-in window, below
  // this chunk's fading-in content. The underlay applies the PRIOR chunk's
  // FINAL camera transform — if the prior chunk was mid-zoom-in, we render
  // it at its end-state zoom, not at 1.0. Otherwise the crossfade snaps
  // from zoomed → un-zoomed → new chunk (jarring). See DESIGN_NOTES for
  // the failure case we fixed here.
  const priorFinalSrc = chunk.priorFinalImageSrc;
  const showPriorUnderlay =
    inCrossfadeIn && priorFinalSrc && priorFinalSrc.length > 0;
  const priorFinalTransform = priorChunk
    ? cameraTransform(
        computeCamera(priorChunk, Math.max(0, priorChunk.durationFrames - 1), fps),
        width,
        height,
      )
    : "translate(0px, 0px) scale(1)";

  return (
    <AbsoluteFill style={{backgroundColor: bg, overflow: "hidden"}}>
      {showPriorUnderlay ? (
        <AbsoluteFill style={{opacity: 1 - crossfadeInOpacity}}>
          <div
            style={{
              width: "100%",
              height: "100%",
              transform: priorFinalTransform,
              transformOrigin: "50% 50%",
            }}
          >
            <Img src={staticFile(priorFinalSrc)} style={IMG_STYLE} />
          </div>
        </AbsoluteFill>
      ) : null}
      <div
        style={{
          width: "100%",
          height: "100%",
          opacity: wipeOutOpacity * crossfadeInOpacity,
        }}
      >
        {content}
        <OverlayLayer
          overlays={chunk.overlays || []}
          canvasWidth={width}
          canvasHeight={height}
        />
      </div>
    </AbsoluteFill>
  );
};

const CrossChunkOverlayLayer: React.FC<{
  overlays: CrossChunkOverlay[];
  canvasWidth: number;
  canvasHeight: number;
}> = ({overlays, canvasWidth, canvasHeight}) => {
  if (!overlays || overlays.length === 0) return null;
  return (
    <>
      {overlays.map((ov, i) => {
        const w = ov.width * canvasWidth;
        const px = ov.x * canvasWidth;
        const py = ov.y * canvasHeight;
        const {tx, ty} = anchorToOffsets(ov.anchor);
        const rot = ov.rotationDeg ?? 0;
        const lower = ov.src.toLowerCase();
        const isVideo =
          lower.endsWith(".mp4") || lower.endsWith(".webm") || lower.endsWith(".mov");
        return (
          <Sequence
            key={`cco-${ov.src}-${i}`}
            from={ov.absStartFrame}
            durationInFrames={Math.max(1, ov.absEndFrame - ov.absStartFrame)}
            layout="none"
          >
            <div
              style={{
                position: "absolute",
                left: px,
                top: py,
                width: w,
                transform: `translate(${tx}, ${ty}) rotate(${rot}deg)`,
                transformOrigin: "center center",
              }}
            >
              {isVideo ? (
                <OffthreadVideo
                  src={staticFile(ov.src)}
                  style={{width: "100%", height: "auto", display: "block"}}
                  muted
                />
              ) : (
                <Img
                  src={staticFile(ov.src)}
                  style={{width: "100%", height: "auto", display: "block"}}
                />
              )}
            </div>
          </Sequence>
        );
      })}
    </>
  );
};

export const SpoolcastComposition: React.FC = () => {
  const chunks = previewData.chunks as Chunk[];
  const crossChunkOverlays =
    ((previewData as {crossChunkOverlays?: CrossChunkOverlay[]}).crossChunkOverlays) ?? [];
  const playbackRate: number =
    (previewData as {playbackRate?: number}).playbackRate ?? 1.0;
  const {width, height} = useVideoConfig();

  return (
    <AbsoluteFill style={{backgroundColor: "#ffffff"}}>
      {chunks.map((chunk, i) => (
        <Sequence
          key={chunk.id}
          from={chunk.startFrame}
          durationInFrames={chunk.durationFrames}
        >
          <ChunkRenderer chunk={chunk} priorChunk={i > 0 ? chunks[i - 1] : null} />
          {chunk.beats.map((beat) => {
            if (!beat.audioSrc) return null;
            return (
              <Sequence
                key={beat.id}
                from={beat.startFrameInChunk}
                durationInFrames={Math.max(
                  1,
                  beat.endFrameInChunk - beat.startFrameInChunk
                )}
              >
                <Audio
                  src={staticFile(beat.audioSrc)}
                  playbackRate={playbackRate}
                />
              </Sequence>
            );
          })}
        </Sequence>
      ))}
      {/* Cross-chunk overlays render after the chunks loop = z-order on top. */}
      <CrossChunkOverlayLayer
        overlays={crossChunkOverlays}
        canvasWidth={width}
        canvasHeight={height}
      />
    </AbsoluteFill>
  );
};
