import React from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
// Generated by scripts/build_preview_data.py — do not edit by hand.
import previewData from "./data/preview-data.json";

/**
 * Spoolcast composition.
 *
 * Per-chunk:
 * - image = pre-gen stroke-reveal frame during wipe-in/wipe-out, otherwise static PNG
 * - camera (x, y, zoom) interpolated per beat from the shot list's
 *   camera_target / camera_zoom / transition_s fields
 * - if no beats in the chunk have camera targets, falls back to a subtle
 *   push-in (1.0 → 1.08 over the chunk duration) so the image never feels dead
 */

export const SPOOLCAST_FPS: number = previewData.fps;
export const SPOOLCAST_DURATION_IN_FRAMES: number = Math.max(
  1,
  previewData.totalFrames
);

// Zone vocabulary → (x, y) center of frame to focus on, as percentages
const ZONES: Record<string, {x: number; y: number}> = {
  center: {x: 50, y: 50},
  "left-third": {x: 17, y: 50},
  "right-third": {x: 83, y: 50},
  "top-third": {x: 50, y: 17},
  "bottom-third": {x: 50, y: 83},
  "upper-middle": {x: 50, y: 30},
  "lower-middle": {x: 50, y: 70},
  "top-left": {x: 20, y: 22},
  "top-right": {x: 80, y: 22},
  "bottom-left": {x: 20, y: 78},
  "bottom-right": {x: 80, y: 78},
  left: {x: 25, y: 50},
  right: {x: 75, y: 50},
  top: {x: 50, y: 25},
  bottom: {x: 50, y: 75},
};

const ZOOMS: Record<string, number> = {
  "": 1.0,
  wide: 1.0,
  medium: 1.35,
  tight: 1.9,
  close: 2.8,
};

type Beat = {
  id: string;
  audioSrc: string;
  audioDurationSec: number;
  startFrameInChunk: number;
  endFrameInChunk: number;
  pauseFrames: number;
  camera?: {
    reason: string;
    target: string;
    zoom: string;
    zoomValue?: number;
    transitionSec: number;
  };
};

type Chunk = {
  id: string;
  imageSrc: string;
  startFrame: number;
  durationFrames: number;
  continuity?: string;
  entrance?: string;
  exit?: string;
  wipeInFrames?: number;
  wipeOutFrames?: number;
  framesDir?: string;
  preGenFrameCount?: number;
  beats: Beat[];
};

type CameraState = {x: number; y: number; zoom: number};

const DEFAULT_CAMERA: CameraState = {x: 50, y: 50, zoom: 1.0};

function cameraFromBeat(beat: Beat): CameraState | null {
  const cam = beat.camera;
  if (!cam || !cam.target) return null;
  const zone = ZONES[cam.target] ?? ZONES.center;
  const zoom = ZOOMS[cam.zoom] ?? 1.0;
  return {x: zone.x, y: zone.y, zoom};
}

function lerpCam(a: CameraState, b: CameraState, t: number): CameraState {
  const k = Math.max(0, Math.min(1, t));
  return {
    x: a.x + (b.x - a.x) * k,
    y: a.y + (b.y - a.y) * k,
    zoom: a.zoom + (b.zoom - a.zoom) * k,
  };
}

function easeInOut(t: number): number {
  return 0.5 - 0.5 * Math.cos(Math.PI * Math.max(0, Math.min(1, t)));
}

/** Returns camera state at a given frame within a chunk, interpolating
 *  between beat targets. If no beats set a camera, returns a subtle push-in. */
function computeCamera(
  chunk: Chunk,
  frameInChunk: number,
  fps: number
): CameraState {
  const beats = chunk.beats;
  const beatCameras = beats.map((b) => cameraFromBeat(b));
  const anySet = beatCameras.some((c) => c !== null);

  if (!anySet) {
    // continues-from-prev / callbacks: hold steady at 1.0. Cuts between
    // similar/continuing images get jarring when each chunk independently
    // pushes in from 1.0 — the camera "rewinds" on every cut.
    const cont = chunk.continuity || "standalone";
    if (cont === "continues-from-prev" || cont.startsWith("callback")) {
      return {x: 50, y: 50, zoom: 1.0};
    }
    // Standalone / new chunks: subtle push-in from 1.0 to 1.08
    const t = Math.max(0, Math.min(1, frameInChunk / Math.max(1, chunk.durationFrames)));
    return {x: 50, y: 50, zoom: 1.0 + 0.08 * t};
  }

  // Find the active beat at this frame (last beat whose start <= frame)
  let active = 0;
  for (let i = 0; i < beats.length; i++) {
    if (beats[i].startFrameInChunk <= frameInChunk) active = i;
  }
  const activeBeat = beats[active];
  const activeCam = beatCameras[active] ?? DEFAULT_CAMERA;

  // Find previous set camera (for interpolation) — walk back to find one
  let prevCam: CameraState = DEFAULT_CAMERA;
  for (let i = active - 1; i >= 0; i--) {
    if (beatCameras[i]) {
      prevCam = beatCameras[i] as CameraState;
      break;
    }
  }
  // If active beat has no camera set, inherit previous
  if (!beatCameras[active]) {
    return prevCam;
  }

  const transitionFrames = Math.round(
    (activeBeat.camera?.transitionSec ?? 0) * fps
  );
  if (transitionFrames <= 0) {
    return activeCam;
  }

  const t = easeInOut(
    (frameInChunk - activeBeat.startFrameInChunk) / transitionFrames
  );
  return lerpCam(prevCam, activeCam, t);
}

/** CSS transform that zooms so the target (x%, y%) of the image appears
 *  at the center of the viewport. */
function cameraTransform(
  cam: CameraState,
  viewportW: number,
  viewportH: number
): string {
  const dx = ((50 - cam.x) / 100) * viewportW * cam.zoom;
  const dy = ((50 - cam.y) / 100) * viewportH * cam.zoom;
  return `translate(${dx}px, ${dy}px) scale(${cam.zoom})`;
}

const IMG_STYLE: React.CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "cover",
  display: "block",
};

const ChunkRenderer: React.FC<{chunk: Chunk}> = ({chunk}) => {
  const frame = useCurrentFrame();
  const {width, height, fps} = useVideoConfig();
  const wipeIn = chunk.wipeInFrames ?? 0;
  const wipeOut = chunk.wipeOutFrames ?? 0;
  const dur = chunk.durationFrames;
  const wipeOutStart = dur - wipeOut;
  const preGen = chunk.preGenFrameCount ?? 0;
  const framesDir = chunk.framesDir ?? "";
  const hasFrames = preGen > 0 && framesDir !== "";

  const inWipeIn = wipeIn > 0 && frame < wipeIn;
  const inWipeOut = wipeOut > 0 && frame >= wipeOutStart;

  let srcPath = chunk.imageSrc;
  if (hasFrames) {
    if (inWipeIn) {
      const progress = Math.min(1, Math.max(0, frame / wipeIn));
      const idx = Math.max(1, Math.min(preGen, Math.ceil(progress * preGen)));
      srcPath = `${framesDir}/frame_${String(idx).padStart(4, "0")}.png`;
    } else if (inWipeOut) {
      const progress = Math.min(
        1,
        Math.max(0, 1 - (frame - wipeOutStart) / wipeOut)
      );
      const idx = Math.max(1, Math.min(preGen, Math.ceil(progress * preGen)));
      srcPath = `${framesDir}/frame_${String(idx).padStart(4, "0")}.png`;
    }
  }

  const cam = computeCamera(chunk, frame, fps);
  const transform = cameraTransform(cam, width, height);

  return (
    <AbsoluteFill style={{backgroundColor: "#ffffff", overflow: "hidden"}}>
      <div
        style={{
          width: "100%",
          height: "100%",
          transform,
          transformOrigin: "50% 50%",
        }}
      >
        <Img src={staticFile(srcPath)} style={IMG_STYLE} />
      </div>
    </AbsoluteFill>
  );
};

export const SpoolcastComposition: React.FC = () => {
  const chunks = previewData.chunks as Chunk[];
  const playbackRate: number =
    (previewData as {playbackRate?: number}).playbackRate ?? 1.0;

  return (
    <AbsoluteFill style={{backgroundColor: "#ffffff"}}>
      {chunks.map((chunk) => (
        <Sequence
          key={chunk.id}
          from={chunk.startFrame}
          durationInFrames={chunk.durationFrames}
        >
          <ChunkRenderer chunk={chunk} />
          {chunk.beats.map((beat) => (
            <Sequence
              key={beat.id}
              from={beat.startFrameInChunk}
              durationInFrames={Math.max(
                1,
                beat.endFrameInChunk - beat.startFrameInChunk
              )}
            >
              <Audio
                src={staticFile(beat.audioSrc)}
                playbackRate={playbackRate}
              />
            </Sequence>
          ))}
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
